### PR TITLE
More description reworks

### PR DESCRIPTION
**Pull request by overdramaticpanromantic**
- Liquid turrets
- Power turrets
- Some factories and drills

### CODE REVIEW

**Review by Catana791 — CHANGES_REQUESTED** [review]
Very nice!
I do have two things though:

1. I don't like saying "paired with the titanium conveyor", these blocks can also be used with other means of item transportation.

2. I dislike continuously using "akin to".  Please re-word this for the files I have left unchecked.

**Comment by overdramaticpanromantic** [comment]
1. Ok.
2. Idk how to check files you have unchecked.

**Comment by Catana791** [comment]
- Arc Storm
- Deracination
- Shatter
- Armageddon
- Uhlan

**Comment by overdramaticpanromantic** [comment]
Should be done now.

**Review by Catana791 — APPROVED** [review]

**Pull request merged**
