### PR TITLE
README Formatting

### PR DESCRIPTION
**Pull request by ElectronicsArchiver**
[Badge Suggestions]: https://img.shields.io/badge/Ｒｅｐｏｓｉｔｏｒｙ_Ｓｕｇｇｅｓｔｉｏｎｓ-609926?style=for-the-badge&logoColor=white&logo=GitHub
[Badge Changes]: https://img.shields.io/badge/Ｃｈａｎｇｅｓ-D81939?style=for-the-badge&logoColor=white&logo=GitLFS
[Badge Robot]: https://img.shields.io/badge/Ｉ＇ｍ_Ｈｕｍａｎ-c84f8c?style=for-the-badge&logoColor=white&logo=RuboCop
[Badge Ask]: https://img.shields.io/badge/Ｐｌｅａｓｅ_Ａｓｋ_Ｍｅ-73398D?style=for-the-badge&logoColor=white&logo=AskUbuntu

[License Badges]: https://github.com/MarkedDown/Licenses
[Widgets]: https://github.com/MarkedDown/Disable/blob/main/Features/Widgets.md
[Tabs]: https://github.com/MarkedDown/Disable/blob/main/Features/Tabs.md
[Wiki]: https://github.com/MarkedDown/Wiki

<br>
<br>

<div align = center>

[<kbd> <br> Please Check The **Preview** <br> </kbd>][Preview]

</div>
  
<br>
<br>

## ![Badge Suggestions]

  <br>

- **Update Description**

  `Content extension mod for Mindustry.`

  <br>

- ***[Disable unused Widgets][Widgets]***:

  - `Packages`

<br>
  
- ***[Why not to use GitHub Wiki][Wiki]***

  <br>

<br>
<br>

## ![Badge Changes]

- General formatting / spacing

- Referenced links

- Added license / discord badge

- Linked resources

<br>
<br>

## ![Badge Ask]

- ***If you have any questions.***

- ***In case you do not agree with some of the changes made in this PR***, <br>
  *please first let me know about them, before disregarding it entirely so*<br>
  *we can possibly find a middle ground and have it not go to waste.*

<br>
<br>

## ![Badge Robot]

<kbd> <br>            No, I'm not a robot.            <br> </kbd>

<kbd> <br>    Yes, you are not the first.    <br> </kbd>

<kbd> <br>     I just made a PR template.     <br> </kbd>

<br>
<br>

[Preview]: https://github.com/ElectronicsArchiver/Fading-Revelations

### CODE REVIEW

**Comment by Catana791** [comment]
I really like what you did. 
I can not merge this pr yet tho because the logo that says 
"Mindustry Extended" when you start the game is outdated.
Thank you for your efforts!

**Comment by ElectronicsArchiver** [comment]
Mhm I see, well tell me once you can I guess?

**Comment by Catana791** [comment]
Of course I will.

**Comment by ElectronicsArchiver** [comment]
@Fresh791 will this do?

**Comment by Catana791** [comment]
This does it perfectly. Do you want to join our Discord? You are more than welcome!

**Comment by ElectronicsArchiver** [comment]
I actually don't have Discord for this account,
only Matrix / Mastodon / Twitter ..
but thanks for the invite~

**Comment by Catana791** [comment]
Hmm if you ever have Discord feel free to join. The server needs people like you! :)

**Comment by ElectronicsArchiver** [comment]
Actually just tried making it again and this time it worked,
well for now, hopefully Discord doesn't lock me out like
with my last account..

*was the reason I didn't use it anymore*

**Comment by Catana791** [comment]
Yes hopefully

**Comment by ElectronicsArchiver** [comment]
Nope, ...

**Comment by ElectronicsArchiver** [comment]
@Fresh791 Might wanna change the repository thumbnail to the new logo as well~

*Though I would put proper padding around it so it isn't streched too much*

**Comment by ElectronicsArchiver** [comment]
@Fresh791 Also your profile description~

**Comment by ElectronicsArchiver** [comment]
@Fresh791 Also also the link to the github pages site,
though, with the theme you are using, links - as you
can see - break quite easily.

https://fresh791.github.io/Fading-Revelations/

Not sure if you even wanna keep it up considering
there isn't any additional content on it..

**Comment by Catana791** [comment]
@ElectronicsArchiver I have recently re-structured the repository so the badges show wrong numbers. Would you be so kind as to fix that?

**Comment by ElectronicsArchiver** [comment]
Lemme check~

**Comment by ElectronicsArchiver** [comment]
@Fresh791 I'm not sure that there is a way to count files in sub-directories with shields io.

A thing that could be done though:
Have a small script written with Deno be run on every file addition / deletion in content folder and have the result be stored in a yaml file that then could be read by shields io

**Comment by Catana791** [comment]
Actually, shields.io can do that. Look!:

**Comment by ElectronicsArchiver** [comment]
Weird, I literally tried that and it showed me `3`..

**Comment by ElectronicsArchiver** [comment]
Nonono, it still doesn't count files from sub-directories, you just switched to another directory..

**Comment by Catana791** [comment]
Right but it counted 10 and there are 10 item turrets in the repo. That means it works?

**Comment by ElectronicsArchiver** [comment]
I'm talking about sub-directories, not files in directories.

For example `content/blocks/effects` counts `4` because there are four folders in that directory but it doesn't count the files in those 4 folders..

**Comment by Catana791** [comment]
Yeah that's true...

**Comment by Catana791** [comment]
And it would look weird having a badge show "other" right? I'll look into it soon.

**Comment by ElectronicsArchiver** [comment]
That's why I suggested this:

> A thing that could be done though:
Have a small script written with Deno be run on every file addition / deletion in content folder and have the result be stored in a yaml file that then could be read by shields io

Btw, I did that for my @OpenModding / Mods repo

**Comment by Catana791** [comment]
Idk how to do that though 😅

**Comment by ElectronicsArchiver** [comment]
Well I can do it for you if you'd like~

**Comment by Catana791** [comment]
Yes please I would GREATLY appreciate that~

**Pull request merged**
