### PR TITLE
Fixed Badge Links

### PR DESCRIPTION
**Pull request by ElectronicsArchiver**
[Badge Suggestions]: https://img.shields.io/badge/Ｒｅｐｏｓｉｔｏｒｙ_Ｓｕｇｇｅｓｔｉｏｎｓ-4b781e?style=for-the-badge&logoColor=white&logo=GitHub&labelColor=609926
[Badge Changes]: https://img.shields.io/badge/Ｃｈａｎｇｅｓ-9e122a?style=for-the-badge&logoColor=white&logo=GitLFS&labelColor=D81939
[Badge GitHub]: https://img.shields.io/badge/ＧｉｔＨｕｂ_Ｎｅｗｃｏｍｅｒｓ-be2e47?style=for-the-badge&logoColor=white&logo=BitWarden&labelColor=FD3A5C
[Badge Robot]: https://img.shields.io/badge/Ｉ＇ｍ_Ｈｕｍａｎ-8c3b63?style=for-the-badge&logoColor=white&logo=RuboCop&labelColor=c84f8c
[Badge Ask]: https://img.shields.io/badge/Ｐｌｅａｓｅ_Ａｓｋ_Ｍｅ-4e2760?style=for-the-badge&logoColor=white&logo=AskUbuntu&labelColor=73398D
[Badge Info]: https://img.shields.io/badge/Ｉｎｆｏｒｍａｔｉｏｎ-01434e?style=for-the-badge&logoColor=white&logo=InternetArchive&labelColor=006272

[Button MarkedDown]: https://img.shields.io/badge/MarkedDown-00b2ff?style=for-the-badge&logoColor=white&logo=Markdown

[License Badges]: https://github.com/MarkedDown/Licenses
[Widgets]: https://github.com/MarkedDown/Disable/blob/main/Features/Widgets.md
[Tabs]: https://github.com/MarkedDown/Disable/blob/main/Features/Tabs.md
[Wiki]: https://github.com/MarkedDown/Wiki
[MarkedDown]: https://github.com/MarkedDown 'How to better use Markdown'

<br>
<br>

## ![Badge Changes]

- Fixed content badge links

<br>
<br>

### CODE REVIEW

**Comment by Catana791** [comment]
Thank you for your work once again :)

**Comment by Catana791** [comment]
Hey @ElectronicsArchiver, I think the workflow tool broke. I ran it a few times over the past few days but it won't update the statistics and thus also not the badges. Could you look into it?

**Comment by ElectronicsArchiver** [comment]
Sure~

**Comment by Catana791** [comment]
Thank you!

**Comment by ElectronicsArchiver** [comment]
@Fresh791 You removed the `content/zones` folder, but didn't adjust the [Tracked.js](https://github.com/Fresh791/Fading-Revelations/blob/main/.github/workflows/Statistics/Tracked.js) file

**Comment by Catana791** [comment]
Okay I removed the maps part in tracked.js so now it should work. I am running it rn

**Comment by Catana791** [comment]
Yes it works again. Thank you!

**Comment by ElectronicsArchiver** [comment]
If the zones statistic is now gone, you should also remove the badge~

**Comment by Catana791** [comment]
Yes, I did that. Thanks again!

**Pull request merged**
