### PR TITLE
Code Refactoring, Formatted Manifest

### PR DESCRIPTION
**Pull request by ElectronicsArchiver**
[Badge Suggestions]: https://img.shields.io/badge/Ｒｅｐｏｓｉｔｏｒｙ_Ｓｕｇｇｅｓｔｉｏｎｓ-609926?style=for-the-badge&logoColor=white&logo=GitHub
[Badge Changes]: https://img.shields.io/badge/Ｃｈａｎｇｅｓ-D81939?style=for-the-badge&logoColor=white&logo=GitLFS
[Badge Robot]: https://img.shields.io/badge/Ｉ＇ｍ_Ｈｕｍａｎ-c84f8c?style=for-the-badge&logoColor=white&logo=RuboCop
[Badge Ask]: https://img.shields.io/badge/Ｐｌｅａｓｅ_Ａｓｋ_Ｍｅ-73398D?style=for-the-badge&logoColor=white&logo=AskUbuntu

[License Badges]: https://github.com/MarkedDown/Licenses
[Widgets]: https://github.com/MarkedDown/Disable/blob/main/Features/Widgets.md
[Tabs]: https://github.com/MarkedDown/Disable/blob/main/Features/Tabs.md
[Wiki]: https://github.com/MarkedDown/Wiki

<br>
<br>

<div align = center>

fade

</div>
  

<br>
<br>

## ![Badge Changes]

- Added github preview

  *In the github folder*

- Refactored js code

  *Didn't show any errors for me, please check~*

- Formatted manifest
  
  *As seen in the screenshot*

- Added editorconfig

  *Only added js / hjson,*
  *add more as needed.*

<br>
<br>

### CODE REVIEW

**Comment by ElectronicsArchiver** [comment]
Btw, the `mindustry-mod-v6` shouldn't be used,
use `mindustry-mod` instead, at least that's
what the listing repo describes:

https://github.com/Anuken/MindustryMods

**Comment by Catana791** [comment]
Okay I will look into your changes tomorrow and decide whether or not I like them. Thank you!

**Comment by ElectronicsArchiver** [comment]
Btw, how far are you with upgrading to v7?

**Comment by Catana791** [comment]
The upgrade is done. There are a few things that are not perfect but the mod works fine in v7. For this purpose, I made a separate repository that has the mod for v7. Until v7 officially comes out, players should use that version. 
Once v7 comes out officially and is no longer in alpha/beta, etc., the main repo will migrate to v7.

**Comment by ElectronicsArchiver** [comment]
I see, nice nice.
Why not just make a v7 branch btw?

**Comment by Catana791** [comment]
Well...
That would have been too easy.
I didn't even think of that 😅

**Comment by ElectronicsArchiver** [comment]
Btw, would you know what ecmascript version mindustry uses?
So unfortunate that it's written in Java ...
If it was a webapp it could run modern Javascript..

**Comment by Catana791** [comment]
True.

**Comment by Catana791** [comment]
And no, I don't know that sorry.

**Comment by ElectronicsArchiver** [comment]
No `??`, `.?`, `...`, `iterators` it seem :c

**Comment by ElectronicsArchiver** [comment]
> And no, I don't know that sorry.

Thanks anyways~

**Comment by Catana791** [comment]
Haha nw

**Comment by Catana791** [comment]
And btw did you already join the discord?

**Comment by ElectronicsArchiver** [comment]
Nope, Discord locked me out again~

Would be cool to have a bridge to matrix,
though I have never looked into how to do it..

**Comment by Catana791** [comment]
I see. That is unfortunate I had liked to have you there. Nw tho, maybe some other time.

**Comment by ElectronicsArchiver** [comment]
Well if you need me for something you can just 
@ me here or on my profile or something~

On that note, I started a new little project
regarding modding: https://github.com/OpenModding

The modlist currently only contains raft mods,
guess I'll do Mindustry stuff next, not that
there is much of a need for it in the regard
of listing them since they all use the
`mindustry-mod` tag, but guess I'll still do
it to get an overview..

**Comment by Catana791** [comment]
Thank you for doing all this work. However, I don't think that changes like these are actually nessecary for a mod this small. If I ever want to come back to this, am I allowed to do so by you? 
Again, this is not meant to be a thing against you. I hope you won't be mad about this and me.

**Comment by ElectronicsArchiver** [comment]
> I don't think that changes like these are actually nessecary for a mod this small. 

Not sure how the size of the mod plays a role in this~

> If I ever want to come back to this, am I allowed to do so by you?

What do you mean, re-open the PR or asak me for help?

Either way, sure.

**Comment by Catana791** [comment]
Yes exactly I meant re-opening the pr or asking you. Thank you and again, nothing personal!

**Review by Catana791 — COMMENTED** [review]
I would like to come back to this. 
I really like the changes in the mod.hjson, the github preview and the editorconfig are also great, however, I don't like the font used in the mod.hjson and the gold-exchanger script was not needed so I deleted that.
Your changes don't change the functionatlity of the code, they just make it more readable if I understood it correctly?

**Comment by Catana791** [comment]
If you could change it to only be:
editorconfig,
cleaned up main.js, music.js and outpost.js,
github preview,
mod.hjson changes with different font

I would merge this pr instantly. The rest, I don't need.
Also, sorry to ask this again but the script changes are just for readability and don't change any functionality right?

**Comment by ElectronicsArchiver** [comment]
> Also, sorry to ask this again but the script changes are just for readability and don't change any functionality right?

Yes, refactoring / formatting usually doesn't add / remove feataurres and the like, of course bugs can get fixed through it~

**Comment by ElectronicsArchiver** [comment]
> I don't like the font used in the mod.hjson
Sure, thought that is not a differrent font,
that would be impossible for me to do, it's 
simply `fullwidth characters`~

https://unicode-table.com/en/blocks/halfwidth-and-fullwidth-forms/

**Comment by ElectronicsArchiver** [comment]
Btw, are the color codes broken for you as well?
For me the text in the mod preview menu is all white~

**Comment by Catana791** [comment]
Yes they are broken for me too

**Comment by Catana791** [comment]
Thank you for your work, i can merge it now. How much do I owe you? xD

**Comment by ElectronicsArchiver** [comment]
> How much do I owe you? xD

lmao

**Comment by Catana791** [comment]
Btw, 1 question: Can you do the logo that you see on the start screen of the game for this mod? 
grafik
Rn it says this, but I would like it to say 
< Mindustry >
< Fading Revelations >

that would be awesome!

**Comment by ElectronicsArchiver** [comment]
@Fresh791 Btw, you haven't set the repository preview to the new one~
https://github.com/Fresh791/Fading-Revelations/blob/main/github/Preview.png

**Comment by Catana791** [comment]
@ElectronicsArchiver Thanks for reminding me, I did it just now.

**Comment by ElectronicsArchiver** [comment]
@Fresh791 Btw, btw, are you gonna disable the `packages` / `environment` widgets in the repo sidebar?

packages unused. <br>
environments redundant. <br>

**Comment by Catana791** [comment]
They are now disabled

**Pull request merged**
