### PR TITLE
Wrote Content Statistics Workflow / Tool

### PR DESCRIPTION
**Pull request by ElectronicsArchiver**
[Badge Suggestions]: https://img.shields.io/badge/Ｒｅｐｏｓｉｔｏｒｙ_Ｓｕｇｇｅｓｔｉｏｎｓ-4b781e?style=for-the-badge&logoColor=white&logo=GitHub&labelColor=609926
[Badge Changes]: https://img.shields.io/badge/Ｃｈａｎｇｅｓ-9e122a?style=for-the-badge&logoColor=white&logo=GitLFS&labelColor=D81939
[Badge GitHub]: https://img.shields.io/badge/ＧｉｔＨｕｂ_Ｎｅｗｃｏｍｅｒｓ-be2e47?style=for-the-badge&logoColor=white&logo=BitWarden&labelColor=FD3A5C
[Badge Robot]: https://img.shields.io/badge/Ｉ＇ｍ_Ｈｕｍａｎ-8c3b63?style=for-the-badge&logoColor=white&logo=RuboCop&labelColor=c84f8c
[Badge Ask]: https://img.shields.io/badge/Ｐｌｅａｓｅ_Ａｓｋ_Ｍｅ-4e2760?style=for-the-badge&logoColor=white&logo=AskUbuntu&labelColor=73398D
[Badge Info]: https://img.shields.io/badge/Ｉｎｆｏｒｍａｔｉｏｎ-01434e?style=for-the-badge&logoColor=white&logo=InternetArchive&labelColor=006272

[Button MarkedDown]: https://img.shields.io/badge/MarkedDown-00b2ff?style=for-the-badge&logoColor=white&logo=Markdown

[License Badges]: https://github.com/MarkedDown/Licenses
[Widgets]: https://github.com/MarkedDown/Disable/blob/main/Features/Widgets.md
[Tabs]: https://github.com/MarkedDown/Disable/blob/main/Features/Tabs.md
[Wiki]: https://github.com/MarkedDown/Wiki
[MarkedDown]: https://github.com/MarkedDown 'How to better use Markdown'

<br>
<br>

<div align = center>

[<kbd> <br> Please Check The **Preview** <br> </kbd>][Preview]

</div>
  
<br>
<br>

## ![Badge Changes]

- Wrote js / deno tool to count files in content folders

  *Trackable items are found in `.github/workflows/Statistics/Tracked.js`*

- Adjusted README badge paths to used dynamic shield io badges with the tracked statistics

  *In the preview they will be broken as I set the source URL to your repository and since you don't have the `Statistics.yaml`, they won't work without the PR,*

  *Otherwise they should be fine, if not I will fix them in a subsequent PR*

- Added workflow to run the tool

  - Manually ( Actions tab -> `Run Workflow` )
 
  - Automatically on push
 
    *for every content folder change & `Tracked.js` change*

    *Commented out as it might be overkill, running it manually every so often should be fine~*
  
<br>
<br>

[Preview]: https://github.com/ElectronicsArchiver/Fading-Revelations

### CODE REVIEW

**Comment by Catana791** [comment]
Reads well but why does it show this? Is this a preview thing?

**Comment by ElectronicsArchiver** [comment]
> Reads well but why does it show this? Is this a preview thing?

Yes, like I said, the links point to **your** repository that currently doesn't contain any data file with the stats, once the PR is merged, they should work~

**Comment by Catana791** [comment]
Ah I see. Let me merge it rq. Thanks!!

**Comment by ElectronicsArchiver** [comment]
Gotta do some fixing it seems~

**Comment by Catana791** [comment]
Yes I wanted to just say that. I am so sorry for making you so much trouble...

**Comment by ElectronicsArchiver** [comment]
No problem~

**Comment by Catana791** [comment]
I think your workflow tool isn't quite working as you'd like it to. I just added a new turret yesterday but it didn't change the file and badge. Do you know where this is coming from?

**Comment by ElectronicsArchiver** [comment]
Did you run it?

**Comment by Catana791** [comment]
How do I do that. Sorry!

**Comment by ElectronicsArchiver** [comment]
Repository Page > Actions > Update Content Statistics > Run Workflow

https://github.com/Fresh791/Fading-Revelations/actions/workflows/Statistics.yml

**Comment by ElectronicsArchiver** [comment]
As I described, I added automatic execution as well,
however as it would be overkill and run it quite often,
I disabled it ( commented out )

**Comment by Catana791** [comment]
Ah yes sorry! I know it now!

**Comment by Catana791** [comment]
And after a while, the shield badge will update automatically right?

**Comment by ElectronicsArchiver** [comment]
Yes, shield badges have a cache timer, you can increase it but of course it has a minimum limit, it was 1h I think, let me check.

**Comment by ElectronicsArchiver** [comment]
> Set the HTTP cache lifetime (rules are applied to infer a default value on a per-badge basis, any values specified below the default will be ignored). The legacy name "maxAge" is also supported.

Should be 1h~

**Comment by Catana791** [comment]
Ok thx, sometimes I am a bit dumb please do excuse this.

**Comment by ElectronicsArchiver** [comment]
No problem~

**Pull request merged**
