### PR TITLE
Replaced Old Logo

### PR DESCRIPTION
**Pull request by ElectronicsArchiver**
*Please check*

### CODE REVIEW

**Comment by Catana791** [comment]
Why does it say "Mine"dustry? xD

**Comment by Catana791** [comment]
But yes, this is what I meant, looks great! Still why Minedustry lol (secret collab with Minecraft?) :D

**Comment by ElectronicsArchiver** [comment]
Didn't realize the mistake~

**Comment by Catana791** [comment]
don't worry but if you are so kind as to fix that, I can merge this bc it looks really good

**Comment by Catana791** [comment]
Amazing! Thank you <3

**Pull request merged**
